function toefl_speaking_questions(){
  const apiKey = PropertiesService.getScriptProperties().getProperty('APIKEY');
  const apiUrl = PropertiesService.getScriptProperties().getProperty('ENDPOINT_URL');
  const messages = [{'role': 'user', 'content': 'Could you make a sample problem and model answer to Question 1: independent speaking task in the TOEFL ibt Test? The model answer should be preferably 90-110 words which includes two main reasons and each of them has two or three sentences.'}];
  const headers = {
    'Authorization':'Bearer '+ apiKey,
    'Content-type': 'application/json'
  };

  const options = {
    'muteHttpExceptions' : true, 
    'headers': headers,          
    'method': 'POST',            
    'payload': JSON.stringify({  
      'model': 'gpt-3.5-turbo',  
      'max_tokens' : 1024,       
      'temperature' : 1.0,   // depends on your preferences    
      'messages': messages})
  };

  const response = JSON.parse(UrlFetchApp.fetch(apiUrl, options).getContentText());
  console.log(response.choices[0].message.content);
  
  const recipient = PropertiesService.getScriptProperties().getProperty('EMAIL_ADDRESS');
  const today = new Date();
  const today_year = today.getFullYear() ;
  const today_month = today.getMonth() + 1 ;
  const today_date = today.getDate() ;
  const today_day = today.getDay() ;
  const dayArray = ["Sun","Mon","Tue","Wed","Thu","Fri","Sat"];

  const subject = "Indepndent speaking task generated by ChatGPT (" + today_date + "/" + today_month + "/" + today_year + "," + dayArray[today_day] + ")";
  const body = response.choices[0].message.content;
   GmailApp.sendEmail(recipient, subject, body);
}
